import { useEffect, useState } from 'react';
import { Brain, Copy, Check, X, Sparkles } from 'lucide-react';
import { useChatStore } from '@/store/chatStore';
import { MarkdownRenderer } from '../MarkdownRenderer';
import { toast } from '@/store/uiStore';
import styles from './ThinkingDrawer.module.scss';

export function ThinkingDrawer() {
  const { activeDrawerThought, setActiveDrawerThought, messages } = useChatStore();
  const [copied, setCopied] = useState(false);

  // Close on Escape key
  useEffect(() => {
    const handleKeyDown = (e) => {
      if (e.key === 'Escape') {
        setActiveDrawerThought(null);
      }
    };

    if (activeDrawerThought) {
      window.addEventListener('keydown', handleKeyDown);
    }
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [activeDrawerThought, setActiveDrawerThought]);

  if (!activeDrawerThought) {
    return null;
  }

  // If activeDrawerThought is a messageId, resolve live thoughts from messages; otherwise use as raw string
  const matchedMessage = messages.find(
    (m) => m._id === activeDrawerThought || m.thoughts === activeDrawerThought,
  );
  const thoughtText = matchedMessage?.thoughts || activeDrawerThought;

  const handleCopy = async () => {
    if (!thoughtText) return;
    try {
      await navigator.clipboard.writeText(thoughtText);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
      toast.success('Thoughts copied to clipboard');
    } catch {
      toast.error('Failed to copy');
    }
  };

  return (
    <>
      <div
        className={styles.backdrop}
        onClick={() => setActiveDrawerThought(null)}
        role="presentation"
        aria-hidden="true"
      />
      <aside
        className={styles.drawer}
        role="dialog"
        aria-modal="true"
        aria-label="AI Reasoning Process"
      >
        <header className={styles.header}>
          <div className={styles.titleArea}>
            <Brain size={18} className={styles.brainIcon} />
            <h3 className={styles.title}>AI Reasoning & Thoughts</h3>
          </div>
          <div className={styles.headerActions}>
            <button
              type="button"
              className={styles.iconBtn}
              onClick={handleCopy}
              title="Copy thinking trace"
              aria-label="Copy thinking trace"
            >
              {copied ? <Check size={16} /> : <Copy size={16} />}
            </button>
            <button
              type="button"
              className={styles.iconBtn}
              onClick={() => setActiveDrawerThought(null)}
              title="Close drawer"
              aria-label="Close drawer"
            >
              <X size={18} />
            </button>
          </div>
        </header>

        <div className={styles.body}>
          <div className={styles.metaInfo}>
            <Sparkles size={14} className={styles.sparkleIcon} />
            <span>
              This is the step-by-step reasoning generated by Gemini before formulating the final
              answer.
            </span>
          </div>

          <div className={styles.contentWrapper}>
            {thoughtText ? (
              <MarkdownRenderer content={thoughtText} />
            ) : (
              <div className={styles.emptyState}>
                <Brain size={24} />
                <p>No thought tokens recorded for this message.</p>
              </div>
            )}
          </div>
        </div>
      </aside>
    </>
  );
}
